apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  lables:
    name: worker-app-pod
    app: demo-voting-app

spec:
  containers:
  - name: worker-app
    image: dockertest00.azurecr.io/workerapp
